# generated by datamodel-codegen:
#   filename:  n8n-openapi.yml
#   timestamp: 2026-04-21T15:43:21+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    EmailStr,
    Field,
    RootModel,
    constr,
)


class Audit(BaseModel):
    Credentials_Risk_Report: dict[str, Any] | None = Field(
        None,
        alias="Credentials Risk Report",
        examples=[
            {
                "risk": "credentials",
                "sections": [
                    {
                        "title": "Credentials not used in any workflow",
                        "description": "These credentials are not used in any workflow. Keeping unused credentials in your instance is an unneeded security risk.",
                        "recommendation": "Consider deleting these credentials if you no longer need them.",
                        "location": [{"kind": "credential", "id": "1", "name": "My Test Account"}],
                    }
                ],
            }
        ],
    )
    Database_Risk_Report: dict[str, Any] | None = Field(
        None,
        alias="Database Risk Report",
        examples=[
            {
                "risk": "database",
                "sections": [
                    {
                        "title": 'Expressions in "Execute Query" fields in SQL nodes',
                        "description": 'This SQL node has an expression in the "Query" field of an "Execute Query" operation. Building a SQL query with an expression may lead to a SQL injection attack.',
                        "recommendation": 'Consider using the "Query Parameters" field to pass parameters to the query',
                        'or validating the input of the expression in the "Query" field.': None,
                        "location": [
                            {
                                "kind": "node",
                                "workflowId": "1",
                                "workflowName": "My Workflow",
                                "nodeId": "51eb5852-ce0b-4806-b4ff-e41322a4041a",
                                "nodeName": "MySQL",
                                "nodeType": "n8n-nodes-base.mySql",
                            }
                        ],
                    }
                ],
            }
        ],
    )
    Filesystem_Risk_Report: dict[str, Any] | None = Field(
        None,
        alias="Filesystem Risk Report",
        examples=[
            {
                "risk": "filesystem",
                "sections": [
                    {
                        "title": "Nodes that interact with the filesystem",
                        "description": "This node reads from and writes to any accessible file in the host filesystem. Sensitive file content may be manipulated through a node operation.",
                        "recommendation": "Consider protecting any sensitive files in the host filesystem",
                        "or refactoring the workflow so that it does not require host filesystem interaction.": None,
                        "location": [
                            {
                                "kind": "node",
                                "workflowId": "1",
                                "workflowName": "My Workflow",
                                "nodeId": "51eb5852-ce0b-4806-b4ff-e41322a4041a",
                                "nodeName": "Ready Binary file",
                                "nodeType": "n8n-nodes-base.readBinaryFile",
                            }
                        ],
                    }
                ],
            }
        ],
    )
    Nodes_Risk_Report: dict[str, Any] | None = Field(
        None,
        alias="Nodes Risk Report",
        examples=[
            {
                "risk": "nodes",
                "sections": [
                    {
                        "title": "Community nodes",
                        "description": "This node is sourced from the community. Community nodes are not vetted by the n8n team and have full access to the host system.",
                        "recommendation": "Consider reviewing the source code in any community nodes installed in this n8n instance",
                        "and uninstalling any community nodes no longer used.": None,
                        "location": [
                            {
                                "kind": "community",
                                "nodeType": "n8n-nodes-test.test",
                                "packageUrl": "https://www.npmjs.com/package/n8n-nodes-test",
                            }
                        ],
                    }
                ],
            }
        ],
    )
    Instance_Risk_Report: dict[str, Any] | None = Field(
        None,
        alias="Instance Risk Report",
        examples=[
            {
                "risk": "execution",
                "sections": [
                    {
                        "title": "Unprotected webhooks in instance",
                        "description": 'These webhook nodes have the "Authentication" field set to "None" and are not directly connected to a node to validate the payload. Every unprotected webhook allows your workflow to be called by any third party who knows the webhook URL.',
                        "recommendation": 'Consider setting the "Authentication" field to an option other than "None"',
                        "or validating the payload with one of the following nodes.": None,
                        "location": [
                            {
                                "kind": "community",
                                "nodeType": "n8n-nodes-test.test",
                                "packageUrl": "https://www.npmjs.com/package/n8n-nodes-test",
                            }
                        ],
                    }
                ],
            }
        ],
    )


class CreateCredentialResponse(BaseModel):
    id: str = Field(..., examples=["vHxaz5UaCghVYl9C"])
    name: str = Field(..., examples=["John's Github account"])
    type: str = Field(..., examples=["githubApi"])
    createdAt: AwareDatetime = Field(..., examples=["2022-04-29T11:02:29.842Z"])
    updatedAt: AwareDatetime = Field(..., examples=["2022-04-29T11:02:29.842Z"])


class CredentialSharedItem(BaseModel):
    id: str = Field(..., description="Project ID")
    name: str = Field(..., description="Project name")
    role: str = Field(
        ...,
        description="Role of the credential in this project (e.g. credential:owner)",
    )
    createdAt: AwareDatetime = Field(
        ..., description="When the credential was shared with this project"
    )
    updatedAt: AwareDatetime = Field(..., description="When the sharing was last updated")


class CredentialListItem(CreateCredentialResponse):
    shared: list[CredentialSharedItem] = Field(
        ...,
        description="Shared entries (project id, name, role, createdAt, updatedAt) from the credential's shared relation",
    )


class CredentialList(BaseModel):
    data: list[CredentialListItem] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through credentials by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class Credential(BaseModel):
    id: str | None = Field(None, examples=["R2DjclaysHbqn778"])
    name: str = Field(..., examples=["Joe's Github Credentials"])
    type: str = Field(..., examples=["githubApi"])
    data: dict[str, Any] = Field(
        ..., examples=[{"accessToken": "ada612vad6fa5df4adf5a5dsf4389adsf76da7s"}]
    )
    isResolvable: bool | None = Field(
        None,
        description="Whether this credential has resolvable fields",
        examples=[False],
    )
    createdAt: AwareDatetime | None = Field(None, examples=["2022-04-29T11:02:29.842Z"])
    updatedAt: AwareDatetime | None = Field(None, examples=["2022-04-29T11:02:29.842Z"])


class UpdateCredentialRequest(BaseModel):
    name: str | None = Field(
        None,
        description="The name of the credential",
        examples=["Updated Credential Name"],
    )
    type: str | None = Field(
        None,
        description="The credential type. If changing type, data must also be provided.",
        examples=["githubApi"],
    )
    data: dict[str, Any] | None = Field(
        None,
        description="The credential data. Required when changing credential type.",
        examples=[{"accessToken": "new_token_value"}],
    )
    isGlobal: bool | None = Field(
        None,
        description="Whether this credential is available globally",
        examples=[False],
    )
    isResolvable: bool | None = Field(
        None,
        description="Whether this credential has resolvable fields",
        examples=[False],
    )
    isPartialData: bool | None = Field(
        False,
        description="If true, unredacts and merges existing credential data with the provided data. If false, replaces the entire data object.",
        examples=[False],
    )


class Mode(StrEnum):
    cli = "cli"
    error = "error"
    integrated = "integrated"
    internal = "internal"
    manual = "manual"
    retry = "retry"
    trigger = "trigger"
    webhook = "webhook"
    evaluation = "evaluation"
    chat = "chat"


class Status(StrEnum):
    canceled = "canceled"
    crashed = "crashed"
    error = "error"
    new = "new"
    running = "running"
    success = "success"
    unknown = "unknown"
    waiting = "waiting"


class Execution(BaseModel):
    id: float | None = Field(None, examples=[1000])
    data: dict[str, Any] | None = None
    finished: bool | None = Field(None, examples=[True])
    mode: Mode | None = None
    retryOf: float | None = None
    retrySuccessId: float | None = Field(None, examples=["2"])
    startedAt: AwareDatetime | None = None
    stoppedAt: AwareDatetime | None = Field(
        None,
        description="The time at which the execution stopped. Will only be null for executions that still have the status 'running'.",
    )
    workflowId: float | None = Field(None, examples=["1000"])
    waitTill: AwareDatetime | None = None
    customData: dict[str, Any] | None = None
    status: Status | None = None


class ExecutionList(BaseModel):
    data: list[Execution] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through executions by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class Tag(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = Field(None, examples=["2tUt1wbLX592XDdX"])
    name: str = Field(..., examples=["Production"])
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class ExecutionTags(RootModel[list[Tag]]):
    root: list[Tag]


class TagId(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., examples=["2tUt1wbLX592XDdX"])


class TagIds(RootModel[list[TagId]]):
    root: list[TagId]


class TagList(BaseModel):
    data: list[Tag] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through tags by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class Node(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = Field(None, examples=["0f5532f9-36ba-4bef-86c7-30d607400b15"])
    name: str | None = Field(None, examples=["Jira"])
    webhookId: str | None = None
    disabled: bool | None = None
    notesInFlow: bool | None = None
    notes: str | None = None
    type: str | None = Field(None, examples=["n8n-nodes-base.jira"])
    typeVersion: float | None = Field(None, examples=[1])
    executeOnce: bool | None = Field(None, examples=[False])
    alwaysOutputData: bool | None = Field(None, examples=[False])
    retryOnFail: bool | None = Field(None, examples=[False])
    maxTries: float | None = None
    waitBetweenTries: float | None = None
    continueOnFail: bool | None = Field(
        None, deprecated=True, description="use onError instead", examples=[False]
    )
    onError: str | None = Field(None, examples=["stopWorkflow"])
    position: list[float] | None = Field(None, examples=[[-100, 80]])
    parameters: dict[str, Any] | None = Field(None, examples=[{"additionalProperties": {}}])
    credentials: dict[str, Any] | None = Field(
        None, examples=[{"jiraSoftwareCloudApi": {"id": "35", "name": "jiraApi"}}]
    )
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class SaveDataErrorExecution(StrEnum):
    all = "all"
    none = "none"


class SaveDataSuccessExecution(StrEnum):
    all = "all"
    none = "none"


class CallerPolicy(StrEnum):
    any = "any"
    none = "none"
    workflowsFromAList = "workflowsFromAList"
    workflowsFromSameOwner = "workflowsFromSameOwner"


class WorkflowSettings(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    saveExecutionProgress: bool | None = None
    saveManualExecutions: bool | None = None
    saveDataErrorExecution: SaveDataErrorExecution | None = None
    saveDataSuccessExecution: SaveDataSuccessExecution | None = None
    executionTimeout: float | None = Field(None, examples=[3600])
    errorWorkflow: str | None = Field(
        None,
        description="The ID of the workflow that contains the error trigger node.",
        examples=["VzqKEW0ShTXA5vPj"],
    )
    timezone: str | None = Field(None, examples=["America/New_York"])
    executionOrder: str | None = Field(None, examples=["v1"])
    callerPolicy: CallerPolicy | None = Field(
        "workflowsFromSameOwner",
        description="Controls which workflows are allowed to call this workflow using the Execute Workflow node.\n\nAvailable options:\n- `any`: Any workflow can call this workflow (no restrictions)\n- `none`: No other workflows can call this workflow (completely blocked)\n- `workflowsFromSameOwner` (default): Only workflows owned by the same project can call this workflow\n  * For personal projects: Only workflows created by the same user\n  * For team projects: Only workflows within the same team project\n- `workflowsFromAList`: Only specific workflows listed in the `callerIds` field can call this workflow\n  * Requires the `callerIds` field to specify which workflow IDs are allowed\n  * See `callerIds` field documentation for usage\n",
        examples=["workflowsFromSameOwner"],
    )
    callerIds: str | None = Field(
        None,
        description="Comma-separated list of workflow IDs allowed to call this workflow (only used with workflowsFromAList policy)",
        examples=["14, 18, 23"],
    )
    timeSavedPerExecution: float | None = Field(
        None, description="Estimated time saved per execution in minutes"
    )
    availableInMCP: bool | None = Field(
        False,
        description="Controls whether this workflow is accessible via the Model Context Protocol (MCP).\n\nWhen enabled, this workflow can be called by MCP clients (AI assistants and other tools\nthat support MCP). This allows external AI tools to discover and execute this workflow\nas part of their capabilities.\n\nRequirements for enabling MCP access:\n- The workflow must be active (not deactivated)\n- The workflow must contain at least one active Webhook node\n- Only webhook-triggered workflows can be exposed via MCP\n\nSecurity note: When a workflow is available in MCP, it can be discovered and executed\nby any MCP client that has the appropriate API credentials for your n8n instance.\n",
        examples=[False],
    )


class Project(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None


class SharedWorkflow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: str | None = Field(None, examples=["workflow:owner"])
    workflowId: str | None = Field(None, examples=["2tUt1wbLX592XDdX"])
    projectId: str | None = Field(None, examples=["2tUt1wbLX592XDdX"])
    project: Project | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class ActiveVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    versionId: str | None = Field(
        None,
        description="Unique identifier for this workflow version",
        examples=["7c6b9e3f-8d4a-4b2c-9f1e-6a5d3b8c7e4f"],
    )
    workflowId: str | None = Field(
        None,
        description="The workflow this version belongs to",
        examples=["2tUt1wbLX592XDdX"],
    )
    nodes: list[Node] | None = None
    connections: dict[str, Any] | None = Field(
        None,
        examples=[{"Jira": {"main": [[{"node": "Jira", "type": "main", "index": 0}]]}}],
    )
    authors: str | None = Field(
        None,
        description="Comma-separated list of author IDs who contributed to this version",
        examples=["1,2,3"],
    )
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None


class Meta(BaseModel):
    onboardingId: str | None = None
    templateId: str | None = None
    instanceId: str | None = None
    templateCredsSetupCompleted: bool | None = None


class Workflow(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = Field(None, examples=["2tUt1wbLX592XDdX"])
    name: str = Field(..., examples=["Workflow 1"])
    active: bool | None = None
    createdAt: AwareDatetime | None = None
    updatedAt: AwareDatetime | None = None
    isArchived: bool | None = None
    versionId: str | None = Field(
        None, description="Current version identifier used for optimistic locking"
    )
    triggerCount: int | None = Field(
        None, description="Number of active trigger nodes in the workflow"
    )
    nodes: list[Node]
    connections: dict[str, Any] = Field(
        ...,
        examples=[{"Jira": {"main": [[{"node": "Jira", "type": "main", "index": 0}]]}}],
    )
    settings: WorkflowSettings
    staticData: str | dict[str, Any] | None = Field(None, examples=[{"lastId": 1}])
    pinData: dict[str, Any] | None = Field(
        None, description="Pinned sample data for nodes, keyed by node name"
    )
    meta: Meta | None = Field(None, description="Workflow metadata such as template information")
    tags: list[Tag] | None = None
    shared: list[SharedWorkflow] | None = None
    activeVersion: ActiveVersion | None = None


class WorkflowList(BaseModel):
    data: list[Workflow] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through workflows by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class WorkflowVersion(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    versionId: str = Field(
        ...,
        description="The version ID of this workflow snapshot",
        examples=["abc123-def456"],
    )
    workflowId: str = Field(
        ...,
        description="The workflow ID this version belongs to",
        examples=["2tUt1wbLX592XDdX"],
    )
    nodes: list[Node] = Field(..., description="Nodes as they were in this version")
    connections: dict[str, Any] = Field(
        ...,
        description="Connections as they were in this version",
        examples=[{"Jira": {"main": [[{"node": "Jira", "type": "main", "index": 0}]]}}],
    )
    authors: str = Field(..., description="Authors who created this version", examples=["John Doe"])
    name: str | None = Field(
        None, description="Workflow name at this version", examples=["Workflow 1"]
    )
    description: str | None = Field(None, description="Workflow description at this version")
    createdAt: AwareDatetime | None = Field(None, description="When this version was created")
    updatedAt: AwareDatetime | None = Field(None, description="When this version was last updated")


class WorkflowTags(RootModel[list[Tag]]):
    root: list[Tag]


class User(BaseModel):
    id: str | None = Field(None, examples=["123e4567-e89b-12d3-a456-426614174000"])
    email: EmailStr = Field(..., examples=["john.doe@company.com"])
    firstName: constr(max_length=32) | None = Field(
        None, description="User's first name", examples=["john"]
    )
    lastName: constr(max_length=32) | None = Field(
        None, description="User's last name", examples=["Doe"]
    )
    isPending: bool | None = Field(
        None,
        description="Whether the user finished setting up their account in response to the invitation (true) or not (false).",
    )
    createdAt: AwareDatetime | None = Field(None, description="Time the user was created.")
    updatedAt: AwareDatetime | None = Field(None, description="Last time the user was updated.")
    role: str | None = Field(None, examples=["global:owner"])


class UserList(BaseModel):
    data: list[User] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through users by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class AutoPublish(StrEnum):
    none = "none"
    all = "all"
    published = "published"


class Pull(BaseModel):
    force: bool | None = Field(None, examples=[True])
    autoPublish: AutoPublish | None = Field(
        "none",
        description="Controls automatic workflow publishing after import:\n- `none`: Keep workflows in their local published state (default)\n- `all`: Publish all imported workflows\n- `published`: Publish only workflows that were published locally before import\n",
        examples=["published"],
    )
    variables: dict[str, Any] | None = Field(None, examples=[{"foo": "bar"}])


class Variables(BaseModel):
    added: list[str] | None = None
    changed: list[str] | None = None


class Credential1(BaseModel):
    id: str | None = None
    name: str | None = None
    type: str | None = None


class Workflow1(BaseModel):
    id: str | None = None
    name: str | None = None


class Tag1(BaseModel):
    id: str | None = None
    name: str | None = None


class Mapping(BaseModel):
    workflowId: str | None = None
    tagId: str | None = None


class Tags(BaseModel):
    tags: list[Tag1] | None = None
    mappings: list[Mapping] | None = None


class ImportResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    variables: Variables | None = None
    credentials: list[Credential1] | None = None
    workflows: list[Workflow1] | None = None
    tags: Tags | None = None


class Project1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    name: str
    type: str | None = None


class Variable(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    key: str
    value: str = Field(..., examples=["test"])
    type: str | None = None
    project: Project1 | None = None


class VariableList(BaseModel):
    data: list[Variable] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through variables by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class Type(StrEnum):
    string = "string"
    number = "number"
    boolean = "boolean"
    date = "date"


class Column(BaseModel):
    id: str | None = Field(None, description="Column ID")
    name: str | None = Field(None, description="Column name")
    type: Type | None = Field(None, description="Column data type")
    index: int | None = Field(None, description="Column position")


class DataTable(BaseModel):
    id: str = Field(..., description="Unique identifier for the data table")
    name: str = Field(..., description="Name of the data table")
    columns: list[Column] = Field(..., description="Column definitions")
    projectId: str = Field(..., description="ID of the project this table belongs to")
    createdAt: AwareDatetime = Field(..., description="Timestamp when the table was created")
    updatedAt: AwareDatetime = Field(..., description="Timestamp when the table was last updated")


class DataTableList(BaseModel):
    data: list[DataTable] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through data tables by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class Type1(StrEnum):
    string = "string"
    number = "number"
    boolean = "boolean"
    date = "date"
    json = "json"


class Column1(BaseModel):
    name: constr(min_length=1) = Field(..., description="Column name")
    type: Type1 = Field(..., description="Column data type")


class CreateDataTableRequest(BaseModel):
    name: constr(min_length=1, max_length=128) = Field(..., description="Name of the data table")
    columns: list[Column1] = Field(..., description="Column definitions for the table")


class UpdateDataTableRequest(BaseModel):
    name: constr(min_length=1, max_length=128) = Field(
        ..., description="New name for the data table"
    )


class DataTableRow(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: int | None = Field(None, description="The row ID (auto-generated)")
    createdAt: AwareDatetime | None = Field(
        None, description="The date and time the row was created"
    )
    updatedAt: AwareDatetime | None = Field(
        None, description="The date and time the row was last updated"
    )


class DataTableRowList(BaseModel):
    data: list[DataTableRow] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through rows by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class ReturnType(StrEnum):
    count = "count"
    id = "id"
    all = "all"


class InsertRowsRequest(BaseModel):
    data: list[dict[str, Any]] = Field(
        ...,
        description="Array of rows to insert. Each row is an object with column names as keys.",
        min_length=1,
    )
    returnType: ReturnType | None = Field(
        "count",
        description="- count: Return only the number of rows inserted\n- id: Return an array of inserted row IDs\n- all: Return the full row data for all inserted rows\n",
    )


class Type2(StrEnum):
    and_ = "and"
    or_ = "or"


class Condition(StrEnum):
    eq = "eq"
    neq = "neq"
    like = "like"
    ilike = "ilike"
    gt = "gt"
    gte = "gte"
    lt = "lt"
    lte = "lte"


class Filter1(BaseModel):
    columnName: str
    condition: Condition
    value: Any


class Filter(BaseModel):
    type: Type2 | None = "and"
    filters: list[Filter1] = Field(..., min_length=1)


class UpdateRowsRequest(BaseModel):
    filter: Filter = Field(..., description="Filter conditions to match rows for update")
    data: dict[str, Any] = Field(..., description="Column values to update")
    returnData: bool | None = Field(
        False,
        description="If true, return the updated rows; if false, return true on success",
    )
    dryRun: bool | None = Field(
        False, description="If true, preview changes without persisting them"
    )


class Filter3(BaseModel):
    columnName: str
    condition: Condition
    value: Any


class Filter2(BaseModel):
    type: Type2 | None = "and"
    filters: list[Filter3] = Field(..., min_length=1)


class UpsertRowRequest(BaseModel):
    filter: Filter2 = Field(
        ...,
        description="Filter conditions to match existing row. If no row matches, a new row is inserted.",
    )
    data: dict[str, Any] = Field(..., description="Column values for the row")
    returnData: bool | None = Field(
        False,
        description="If true, return the upserted row; if false, return true on success",
    )
    dryRun: bool | None = Field(
        False, description="If true, preview changes without persisting them"
    )


class ProjectList(BaseModel):
    data: list[Project1] | None = None
    nextCursor: str | None = Field(
        None,
        description='Paginate through projects by setting the cursor parameter to a nextCursor attribute returned by a previous request. Default value fetches the first "page" of the collection.',
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class ProjectMember(BaseModel):
    id: str | None = Field(
        None,
        description="The user's unique identifier.",
        examples=["123e4567-e89b-12d3-a456-426614174000"],
    )
    email: EmailStr | None = Field(
        None, description="The user's email address.", examples=["john.doe@company.com"]
    )
    firstName: constr(max_length=32) | None = Field(
        None, description="The user's first name.", examples=["john"]
    )
    lastName: constr(max_length=32) | None = Field(
        None, description="The user's last name.", examples=["Doe"]
    )
    createdAt: AwareDatetime | None = Field(None, description="When the user was created.")
    updatedAt: AwareDatetime | None = Field(None, description="When the user was last updated.")
    role: str | None = Field(
        None,
        description="The user's role in the project (e.g. project:admin, project:viewer).",
        examples=["project:viewer"],
    )


class ProjectMemberList(BaseModel):
    data: list[ProjectMember] | None = None
    nextCursor: str | None = Field(
        None,
        description="Paginate through project members by setting the cursor parameter to the nextCursor attribute returned by a previous request. Default value fetches the first page of the collection.",
        examples=["MTIzZTQ1NjctZTg5Yi0xMmQzLWE0NTYtNDI2NjE0MTc0MDA"],
    )


class Error(BaseModel):
    code: str | None = None
    message: str
    description: str | None = None


class Role(BaseModel):
    id: float | None = Field(None, examples=[1])
    name: str | None = Field(None, examples=["owner"])
    scope: str | None = Field(None, examples=["global"])
    createdAt: AwareDatetime | None = Field(None, description="Time the role was created.")
    updatedAt: AwareDatetime | None = Field(None, description="Last time the role was updated.")


class CredentialType(BaseModel):
    displayName: str | None = Field(None, examples=["Email"])
    name: str | None = Field(None, examples=["email"])
    type: str | None = Field(None, examples=["string"])
    default: str | None = Field(None, examples=["string"])
