# generated by datamodel-codegen:
#   filename:  n8n-openapi.yml
#   timestamp: 2026-04-21T15:43:21+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field


class Create(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str | None = None
    key: str
    value: str = Field(..., examples=["test"])
    type: str | None = None
    projectId: str | None = Field(None, examples=["VmwOO9HeTEj20kxM"])
